# To use this docker-compose.yml, run `docker compose up`. If you want to make
# it run in the background, you instead run `docker compose up -d`. If you want
# to run a different example, change the `MODEL_DIR` below to e.g.
# "examples/sugarscape_cg". You can also specify the path to your custom model
# (relative to this Git repository).
# Note: the model directory MUST contain a run.py file.
version: "3"
services:
  systems-models:
    build: .
    image: mesa:dev
    volumes:
      - .:/opt/mesad
    environment:
      MODEL_DIR: .
      MODELS: mythematical
    ports:
      - "127.0.0.1:5001:5001"
